version: 2

sources:
  - name: data_source
    database: globalsuperstore
    tables:
      - name: orders
      - name: peoples
      - name: returns
      - name: tmp_orders

  - name: data_storage
    database: globalsuperstore
    tables:
      - name: order

models:
  - name: order
    columns:
      - name: order_key
        tests:
          - unique
          - not_null
      - name: order_customer_key
        tests:
          - not_null
      - name: order_location_key
        tests:
          - not_null
      - name: order_region_key
        tests:
          - not_null
      - name: order_product_key
        tests:
          - not_null

  - name: country
    columns:
      - name: country_key
        tests:
          - unique
          - not_null
      - name: country_market_key
        tests:
          - not_null

  - name: customer
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null

  - name: location
    columns:
      - name: location_key
        tests:
          - unique
          - not_null
      - name: location_country_key
        tests:
          - not_null

  - name: market
    columns:
      - name: market_key
        tests:
          - unique
          - not_null

  - name: product
    columns:
      - name: product_key
        tests:
          - unique
          - not_null

  - name: region
    columns:
      - name: region_key
        tests:
          - unique
          - not_null
      - name: region_market_key
        tests:
          - not_null